apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: netzsim
      defaultBucket: powerflow
      tlsSkipVerify: true
    secureJsonData:
      token: netzsim-dev-token
