"""Generate docs/API.md from the live OpenAPI schema.

The endpoint reference is extracted from the FastAPI app itself (path,
method, docstring, parameters, request models), so it cannot drift from the
code — rerun after any API change:

    PYTHONPATH=src python scripts/gen_api_doc.py

The prose sections (intro, conventions, WebSocket, result shapes) live in
the templates below; everything under "Endpoint reference" is generated.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from netzsim.config import settings  # noqa: E402

settings.autostart = False

from netzsim.api import app  # noqa: E402

# Endpoint grouping mirrors the router modules (src/netzsim/api/) — matched
# by path prefix, FIRST match wins, so keep the more specific entries first.
GROUPS: list[tuple[str, str, list[str]]] = [
    ("Core", "Health, topology, live results and per-element day curves "
             "(`api/core.py`).",
     ["/health", "/status", "/network", "/state", "/history", "/manual",
      "/node/{bus}/profiles", "/line/{line}/profiles",
      "/trafo/{trafo}/profiles", "/"]),
    ("Engine control", "Start/pause/seek the accelerated-tick loop and the "
                       "real-PV day calendar (`api/control.py`).",
     ["/control/", "/pv/days"]),
    ("Runtime equipment", "Batteries, overload controllers, rONTs and "
                          "per-node DERs, all placed while the simulation "
                          "runs (`api/equipment.py`).",
     ["/batteries", "/battery", "/controllers", "/controller", "/ronts",
      "/ront", "/node/{bus}/der", "/pv", "/ev"]),
    ("Observability & estimation", "Meter placement (per-device TAF "
                                   "fidelity) and the WLS estimation policy "
                                   "(`api/measurements.py`).",
     ["/measurements", "/estimation/"]),
    ("Grid catalog & load generation", "The committed grid dataset, user "
                                       "grid imports, LPG load assignment "
                                       "and the runtime grid swap "
                                       "(`api/grids.py`).",
     ["/grids", "/loadgen/", "/config/"]),
    ("Recording & export", "Session recording of the live step stream and "
                           "the offline bulk export of whole days "
                           "(`api/recordings.py`).",
     ["/recording", "/recordings", "/export"]),
    ("Scenarios", "Save the configured live setup as a recipe file and "
                  "replay it (`api/scenarios.py`).",
     ["/scenarios"]),
]

HEADER = """\
# netzsim REST API

> Generated by `scripts/gen_api_doc.py` from the FastAPI app — do not edit
> the endpoint reference by hand; rerun the script after API changes. The
> always-current interactive version is the built-in Swagger UI at
> **`http://localhost:8000/docs`** (ReDoc at `/redoc`).

Base URL: `http://localhost:8000` (configure with `NETZSIM_HOST`/`NETZSIM_PORT`).
No authentication — netzsim is a local teaching tool. All bodies and
responses are JSON (`Content-Type: application/json`).

## Conventions

- **Bus/line/transformer ids** are pandapower element indices — integers
  matching the order of `grid_structure.buses` (and the insertion order of
  lines/transformers). `/network` is the id directory.
- **Numeric safety**: result floats are rounded to 6 digits and non-finite
  values (NaN/±Inf) become `null`, so every payload parses in a browser.
- **Strict observability** (`NETZSIM_EXPOSE_GROUND_TRUTH=false`): the solved
  ground truth is stripped from `/state`, `/ws`, `/history`, and the
  day-curve endpoints downgrade a requested `view=truth` to the measured
  layer (the `est` view keeps its estimate/measured layers but loses the
  truth arrays).
- **Errors** use FastAPI's standard shape `{"detail": "..."}` with 404
  (unknown element/resource), 409 (conflicting state, e.g. export already
  running), 400 (invalid grid document) and 422 (validation).

## WebSocket `/ws`

`ws://localhost:8000/ws` pushes one JSON **StepResult** per solved step (the
latest result is sent immediately on connect). Client messages are ignored
(keepalive only). The payload equals `GET /state`.

## Result shapes

**StepResult** (per step, `/state` · `/ws` · `/history`): `step`, `day`,
`time_of_day` ("HH:MM"), `converged`, `solve_ms`, `timestamp` (unix s),
`buses[]`, `lines[]`, `trafos[]`, `ext_grids[]`, `summary`, plus the runtime
layers `batteries[]`, `controllers[]`, `ronts[]`, and the observability
projection `measurements` (readings ONLY at placed meters) with
`observed_summary`, and `estimated` (the latest WLS run: `buses/lines/trafos`,
`solve_ms`, `seq`, per-cell results on districts). The truth arrays
(`buses/lines/trafos/ext_grids/summary`) are absent in strict mode.

**Day-curve endpoints** (`/node|line|trafo/{id}/profiles?view=truth|measured|est`)
return per-view layers: the truth curves in the full input raster, the
measured layer only for metered elements in their device's TAF raster
(15-min means for TAF 7, pass-through for TAF 9/10/14), and the estimate in
the pinned estimation raster. Absent layers are `[]`/`null`.

## Endpoint reference
"""


def _resolve(schema: dict, ref: str) -> dict:
    node: dict = schema
    for part in ref.lstrip("#/").split("/"):
        node = node[part]
    return node


def _type_of(prop: dict) -> str:
    if "$ref" in prop:
        return prop["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in prop:
        return " | ".join(_type_of(p) for p in prop["anyOf"])
    t = prop.get("type", "any")
    if t == "array":
        return f"array[{_type_of(prop.get('items', {}))}]"
    if "const" in prop:
        return repr(prop["const"])
    if "enum" in prop:
        return " | ".join(repr(v) for v in prop["enum"])
    return t


def _body_lines(schema: dict, op: dict) -> list[str]:
    body = op.get("requestBody")
    if not body:
        return []
    content = body.get("content", {}).get("application/json", {})
    ref = content.get("schema", {})
    model = _resolve(schema, ref["$ref"]) if "$ref" in ref else ref
    name = ref.get("$ref", "").rsplit("/", 1)[-1] or "body"
    required = set(model.get("required", []))
    out = [f"Body (`{name}`):", "", "| field | type | default |",
           "|---|---|---|"]
    for fname, prop in model.get("properties", {}).items():
        default = ("required" if fname in required
                   else "—" if "default" not in prop
                   else repr(prop["default"]).replace("|", "\\|"))
        out.append(f"| `{fname}` | {_type_of(prop).replace('|', chr(92) + '|')} "
                   f"| {default} |")
    out.append("")
    return out


def _param_lines(op: dict) -> list[str]:
    params = op.get("parameters", [])
    if not params:
        return []
    out = ["| parameter | in | type | required |", "|---|---|---|---|"]
    for p in params:
        out.append(f"| `{p['name']}` | {p['in']} "
                   f"| {_type_of(p.get('schema', {})).replace('|', chr(92) + '|')} "
                   f"| {'yes' if p.get('required') else 'no'} |")
    out.append("")
    return out


def _group_of(path: str) -> str:
    for title, _, prefixes in GROUPS:
        for pre in prefixes:
            if pre == "/":                     # the monitor page: exact only
                if path == "/":
                    return title
            elif path == pre or path == pre.rstrip("/") \
                    or path.startswith(pre if pre.endswith("/") else pre + "/"):
                return title
    return GROUPS[0][0]


def main() -> None:
    schema = app.openapi()
    grouped: dict[str, list[str]] = {title: [] for title, _, _ in GROUPS}
    for path, methods in schema["paths"].items():
        for method, op in methods.items():
            desc = (op.get("description") or "").strip()
            block = [f"### `{method.upper()} {path}`", ""]
            if desc:
                block += [desc, ""]
            block += _param_lines(op)
            block += _body_lines(schema, op)
            grouped[_group_of(path)].append("\n".join(block).rstrip() + "\n")

    parts = [HEADER]
    for title, blurb, _ in GROUPS:
        if not grouped[title]:
            continue
        parts.append(f"\n## {title}\n\n{blurb}\n")
        parts += grouped[title]
    out = ROOT / "docs" / "API.md"
    out.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    n = sum(len(v) for v in grouped.values())
    print(f"wrote {out} ({n} endpoints + WebSocket)")


if __name__ == "__main__":
    main()
